Mntc/criacao script entidades
kvojps/sistema-acs pull request #1
Opened 2023-07-12 22:07 UTC by Emio-eng

A partir dos pedidos da fábrica de software 1, foi criado scripts SQL para a inserção de todas as entidades atuais do sistema.

Os certificados e rascunhos foram feitos a partir de um usuário cadastrado ( que está no insertUsuarios), então todos os dados da inserção são reais.

2023-07-13 20:33 UTC, kvojps commented
@Emio-eng , por favor inserir as imagens do banco populado na descrição do PR.

2023-07-13 20:37 UTC, kvojps requested changes

2023-07-13 20:37 UTC, kvojps commented on database/insertCertificado.sql
> +INSERT INTO certificado (id, titulo, descricao, observacao, data, horas, ch_maxima, ch_total, certificado, status_certificado, requisicao_id, atividade_id)
É necessário passar o arquivo do certificado em array de bytes

2023-07-14 21:31 UTC, Emio-eng commented on database/insertCertificado.sql
> +INSERT INTO certificado (id, titulo, descricao, observacao, data, horas, ch_maxima, ch_total, certificado, status_certificado, requisicao_id, atividade_id)
A alteração foi realizada, irei pedir uma revisão do PR.

2023-07-19 13:48 UTC, kvojps commented
@Emio-eng, levar em consideração as sugestões desse PR [Release Notes - Versão 1.0.0](https://github.com/kvojps/sistema-acs/pull/2#top)

2023-07-19 13:48 UTC, closed without merging